@startuml
title Диаграмма деятельности: Разметка события во время просмотра матча

start

:Пользователь просматривает видео;
:Видео воспроизводится в режиме Playing;

if (Нажата горячая клавиша?) then (Да)
  :Определить тип события по клавише\n(A/D/S или пользовательская);
  :Получить текущий номер кадра\ncurrent_frame = get_current_frame_idx();
  
  if (Режим записи == Dynamic) then (Да)
    if (Запись уже активна?) then (Да)
      :Завершить текущую запись;
      :Вычислить start_frame с учетом pre-roll;
      :Создать объект Marker\n(start_frame, current_frame, event_name);
      :Добавить Marker в коллекцию markers[];
      :Автоматически перейти к start_frame\nseek_frame(start_frame);
      :Отправить сигнал markers_changed.emit();
      :Обновить timeline\nemit timeline_update();
    else (Нет)
      :Начать новую запись;
      :Установить флаг is_recording = true;
      :Сохранить recording_event_name и recording_start_frame;
      :Показать статус "Recording";
      :emit recording_status_changed(event_name, "Recording");
    endif
  else (Fixed Length)
    :Вычислить границы сегмента\n(fixed_duration + pre/post roll);
    :Создать Marker с фиксированной длиной;
    :Добавить в коллекцию markers[];
    :Показать статус "Fixed";
    :emit recording_status_changed(event_name, "Fixed");
    :Перейти к началу сегмента\nseek_frame(start_frame);
  endif
  
  :Отправить сигнал markers_changed.emit();
  :Обновить отображение timeline;
  :Сохранить операцию в Undo стек\npush_command(new AddMarkerCommand());
else (Нет)
  :Продолжить воспроизведение видео;
endif

:Проверить условия завершения;

if (Конец видео?) then (Да)
  :Остановить воспроизведение\npause();
  :Показать финальный кадр;
  stop
else (Нет)
  if (Пользователь нажал Pause/Stop?) then (Да)
    :Остановить воспроизведение;
    :Сохранить текущую позицию;
    stop
  else (Нет)
    :Продолжить цикл воспроизведения;
    detach
  endif
endif

@enduml